CREATE DATABASE lab11;

CREATE TABLE accounts
(
    id      INT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(100) NOT NULL,
    balance DEC(15, 2)   NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO accounts(name, balance)
VALUES ('Qwerty', 5700),
       ('Nqz', 10000);


-- 1
BEGIN;
INSERT INTO accounts(name, balance)
VALUES ('Snowchild', 300);
COMMIT;

BEGIN;
UPDATE accounts
SET balance = balance + 100
WHERE id = 3;
COMMIT;

SELECT *
FROM accounts;


-- 2
CREATE TABLE table1
(
    id INT
);

BEGIN;
INSERT INTO table1
VALUES (1);
SAVEPOINT point1;
INSERT INTO table1
VALUES (2);
ROLLBACK TO point1;
INSERT INTO table1
VALUES (3);
SAVEPOINT point2;
INSERT INTO table1
VALUES (4);
INSERT INTO table1
VALUES (5);
INSERT INTO table1
VALUES (6);
ROLLBACK TO point2;
COMMIT;


-- 3
CREATE OR REPLACE PROCEDURE check_sum(i INTEGER)
AS
$$
BEGIN
    INSERT INTO accounts(name, balance) VALUES ('Margarita', i);
    CASE WHEN (SELECT sum(balance) FROM accounts) < 17000 THEN COMMIT;
        ELSE ROLLBACK ;
        END CASE;
END;
$$ LANGUAGE plpgsql;

CALL check_sum(800);
CALL check_sum(500);


-- 4
BEGIN;
SAVEPOINT point3;
DELETE
FROM table1;
ROLLBACK TO point3;
INSERT INTO table1
VALUES (7);
SAVEPOINT point4;
INSERT INTO table1
VALUES (8);
ROLLBACK TO point4;
INSERT INTO table1
VALUES (9);
SAVEPOINT point5;
INSERT INTO table1
VALUES (9);
INSERT INTO table1
VALUES (10);
ROLLBACK TO point5;
INSERT INTO table1
VALUES (11);
COMMIT;
